videojs.addLanguage('ca', {
	"Audio Player": "Reproductor d'àudio",
	"Video Player": "Reproductor de vídeo",
	"Play": "Reprodueix",
	"Pause": "Pausa",
	"Replay": "Torna a reproduir",
	"Current Time": "Instant actual",
	"Duration": "Durada",
	"Remaining Time": "Temps restant",
	"Stream Type": "Tipus de flux",
	"LIVE": "EN DIRECTE",
	"Seek to live, currently behind live": "Vés a la part en directe, ara vas més endarrere",
	"Seek to live, currently playing live": "Vés a la part en directe, ara es reprodueix en directe",
	"Loaded": "S'ha carregat",
	"Progress": "Progrés",
	"Progress Bar": "Barra de progrés",
	"progress bar timing: currentTime={1} duration={2}": "{1} de {2}",
	"Fullscreen": "Pantalla completa",
	"Non-Fullscreen": "Surt de la pantalla completa",
	"Mute": "Silencia",
	"Unmute": "Deixa de silenciar",
	"Playback Rate": "Velocitat de reproducció",
	"Subtitles": "Subtítols",
	"subtitles off": "subtítols desactivats",
	"Captions": "Subtítols",
	"captions off": "subtítols desactivats",
	"Chapters": "Capítols",
	"Descriptions": "Descripcions",
	"descriptions off": "descripcions desactivades",
	"Audio Track": "Pista d'àudio",
	"Volume Level": "Volum",
	"You aborted the media playback": "Heu aturat la reproducció de l'element multimèdia",
	"A network error caused the media download to fail part-way.": "Un error de la xarxa ha provocat que la baixada de l'element multimèdia fallés.",
	"The media could not be loaded, either because the server or network failed or because the format is not supported.": "No s'ha pogut carregar l'element multimèdia: pot ser que el servidor o la xarxa hagin fallat, o que el format no estigui suportat.",
	"The media playback was aborted due to a corruption problem or because the media used features your browser did not support.": "S'ha aturat la reproducció de l'element multimèdia a causa d'un problema de corrupció o perquè l'element fa servir funcionalitats que el vostre navegador no suporta.",
	"No compatible source was found for this media.": "No s'ha trobat cap origen compatible per a aquest element multimèdia.",
	"The media is encrypted and we do not have the keys to decrypt it.": "L'element multimèdia està xifrat i no en tenim les claus per a desxifrar-lo.",
	"Play Video": "Reprodueix el vídeo",
	"Close": "Tanca",
	"Close Modal Dialog": "Tanca la finestra modal",
	"Modal Window": "Finestra modal",
	"This is a modal window": "Això és una finestra modal",
	"This modal can be closed by pressing the Escape key or activating the close button.": "Aquesta finestra modal es pot tancar prement la tecla Esc o el botó de tancament.",
	", opens captions settings dialog": ", opens captions settings dialog",
	", opens subtitles settings dialog": ", opens subtitles settings dialog",
	", opens descriptions settings dialog": ", opens descriptions settings dialog",
	", selected": ", selected",
	"captions settings": "captions settings",
	"subtitles settings": "subtitles settings",
	"descriptions settings": "descriptions settings",
	"Text": "Text",
	"White": "White",
	"Black": "Black",
	"Red": "Red",
	"Green": "Green",
	"Blue": "Blue",
	"Yellow": "Yellow",
	"Magenta": "Magenta",
	"Cyan": "Cyan",
	"Background": "Background",
	"Window": "Window",
	"Transparent": "Transparent",
	"Semi-Transparent": "Semi-Transparent",
	"Opaque": "Opaque",
	"Font Size": "Font Size",
	"Text Edge Style": "Text Edge Style",
	"None": "None",
	"Raised": "Raised",
	"Depressed": "Depressed",
	"Uniform": "Uniform",
	"Dropshadow": "Dropshadow",
	"Font Family": "Font Family",
	"Proportional Sans-Serif": "Proportional Sans-Serif",
	"Monospace Sans-Serif": "Monospace Sans-Serif",
	"Proportional Serif": "Proportional Serif",
	"Monospace Serif": "Monospace Serif",
	"Casual": "Casual",
	"Script": "Script",
	"Small Caps": "Small Caps",
	"Reset": "Reset",
	"restore all settings to the default values": "restore all settings to the default values",
	"Done": "Done",
	"Caption Settings Dialog": "Caption Settings Dialog",
	"Beginning of dialog window. Escape will cancel and close the window.": "Beginning of dialog window. Escape will cancel and close the window.",
	"End of dialog window.": "End of dialog window.",
	"{1} is loading.": "{1} està carregant.",
	"Exit Picture-in-Picture": "Exit Picture-in-Picture",
	"Picture-in-Picture": "Picture-in-Picture",
	"Open Chromecast menu": "Emet"
});
